# Generated by Django 4.2.27 on 2025-12-30 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapistavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physiotherapistavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='service',
            field=models.CharField(choices=[('general', 'General Query'), ('elderly', 'Elderly Care'), ('ortho', 'Orthopedic Physiotherapy'), ('neuro', 'Neuro Rehabilitation'), ('post_surgery', 'Post Surgery Rehab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='physiotherapistavailability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
