# Generated by Django 4.2.27 on 2025-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_physiotherapistavailability_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapistavailability',
            name='manually_closed',
            field=models.BooleanField(default=False),
        ),
    ]
